rsksmart/rif-relay-client

- .gitignore
This PR adds the package-lock.json to the gitignore file
> Adding package-lock.json into gitignore file

- .gitignore
- package.json
This PR fixes a bug on the dependencies when someone uses this repository as a library.
> Bug fix/pp 55/fixing missing dependencies

- package.json
- Change the package name
- We want the package name to be in the format `@rsksmart/<package_name>`
> Change the package name

- package.json
- Release
- Release
- [Jira issue](https://rsklabs.atlassian.net/browse/PP-204)
> 0.0.2-alpha.8

- src/Configurator.ts
- [This](https://github.com/rsksmart/rif-relay/blob/develop/test/relayclient/Configurator.test.ts#L25) test in rif-relay is failling. This change aims to solve the issue.
- To discard a deeper problem. 
- https://rsklabs.atlassian.net/browse/PP-274
> PP-274: fix configurator test

- src/api/common/HttpWrapper.ts
- test/api/common/HttpWrapper.test.ts
- re-add Enveloping module
- adapt it to using ethers
- write tests
- [Ticket](https://rsklabs.atlassian.net/browse/PP-494)
- [Parent](https://rsklabs.atlassian.net/browse/PP-354)
> feat(ethers): adapt HttpWrapper module

- package.json
- src/HttpClient.ts
- src/HttpWrapper.ts
- src/RelayClient.ts
- test/HttpClient.test.ts
- test/RelayClient.test.ts
- test/utils.ts
-   Consume the endpoint from the Relay Server for gas estimation
-  Simplify the gas estimation
- Centralize the source of the gas estimation
-   [Jira Issue](https://rsklabs.atlassian.net/browse/PP-508)
> PP-508/fees-from-server

- src/KnownRelaysManager.ts
- test/KnownRelaysManager.test.ts
- rewrite known relays manager
- code migration
- (optional: include links to other issues, PRs, tickets, etc)
> PP-495: Change the KnownRelaysManager to support ethers.js

- package.json
- src/RelayClient.ts
- src/api/ExchangeApi.ts
- Expose the getPingResponse
- To be able to use it in the SDK
- [Jira 504](https://rsklabs.atlassian.net/browse/PP-504)
- https://github.com/rsksmart/rif-relay-contracts/pull/91
- https://github.com/rsksmart/rif-relay-common/pull/43
> PP-504/remove-worker-configuration

- package.json
- update package.json version and rif-relay-contracts dependency
- to use the updated version of the contracts and to release a new version of the common
> PP-105: signature verification on createUserSmartWallet

- package.json
- src/Configurator.ts
- src/Enveloping.ts
- src/RelayClient.ts
- test/HttpClient.test.ts
- test/RelayClient.test.ts
- (describe the changes)
- (the reason these changes are wanted)
- (optional: include links to other issues, PRs, tickets, etc)
> REL-004: Expiration mechanism

- .eslintrc.cjs
- package.json
- src/RelayClient.ts
- test/RelayClient.test.ts
- Add relay client
- Re implement _calculateGasPrice
- [PP-607](https://rsklabs.atlassian.net/browse/PP-607)
> PP-607/RelayClient: _calculateGasPrice 

- package.json
- src/RelayClient.ts
- test/AccountManager.test.ts
- test/RelayClient.test.ts
- Add relay client
- Re implement _validateSmartWallet
- [PP-602](https://rsklabs.atlassian.net/browse/PP-602)
- https://github.com/rsksmart/rif-relay-contracts/pulls
> PP-602/RelayClient: _validateSmartWallet

- package.json
- src/RelayClient.ts
- src/api/common/HttpClient.ts
- src/common/relayRequest.types.ts
- src/common/utility.types.ts
- src/constants/errorMessages.ts
- test/RelayClient.test.ts
- test/request.fakes.ts
- adds _getRelayRequestDetails function
- prevents building the request multiple times across the RelayClient class
- [PP-617](https://rsklabs.atlassian.net/browse/PP-617)
> feat(ethers): unifies relayRequest composition in relay client

- src/RelayClient.ts
- src/gasEstimator/gasEstimator.ts
- src/gasEstimator/index.ts
- src/gasEstimator/utils.ts
- src/utils.ts
- test/gasEstimator/gasEstimator.test.ts
- Port the GasEstimator from rif-relay-server to rif-relay-client
- Project refactoring
- [PP-601](https://rsklabs.atlassian.net/browse/PP-601)
> PP601: Port the GasEstimator from the server to the client

- src/RelayClient.ts
- src/common/index.ts
- src/common/relayClient.types.ts
- src/gasEstimator/utils.ts
- src/index.ts
- test/RelayClient.test.ts
- test/request.fakes.ts
- expose components to be consumed
- componentes are going to be used by the server and dApp
-  [PP-627](https://rsklabs.atlassian.net/browse/PP-627)
> refactor: expose components

- src/RelayProvider.ts
- src/handlers/RelayProvider.ts
- src/utils.ts
- test/RelayProvider.test.ts
- test/handlers/RelayProvider.test.ts
- test/utils.test.ts
Change RelayProvider.ts to ethers version
Part of a general upgrade
https://rsklabs.atlassian.net/jira/software/projects/PP/boards/84/backlog?selectedIssue=PP-498
> PP-498 relay provider

- package.json
- src/AccountManager.ts
- src/RelayClient.ts
- src/RelayProvider.ts
- src/api/common/HttpClient.ts
- src/common/clientConfigurator.ts
- src/common/config.types.ts
- src/discovery/utils.ts
- src/gasEstimator/gasEstimator.ts
- src/index.ts
- src/utils.ts
- test/AccountManager.test.ts
- test/api/common/HttpClient.test.ts
- Migrate utility files used by the server
- Necessary to integration test
- [PP-642](https://rsklabs.atlassian.net/browse/PP-642)
> PP-642/migrate-test-utils-server

- package.json
- Bump version
- The previous one isn't valid
> 2.0.0-beta.1

- package.json
- src/api/common/HttpClient.ts
- src/api/common/HttpWrapper.ts
- src/api/pricer/CoinBase.ts
- test/api/common/HttpClient.test.ts
- test/api/common/HttpWrapper.test.ts
- test/api/pricer/CoinBase.test.ts
Replace axios with SuperAgent
Request library must be compatible on both client and server
> PP-645:replace axios

- package.json
- src/RelayPricer.ts
- src/api/CoinBase.ts
- src/api/CoinGecko.ts
- test/api/CoinBase.test.ts
- test/api/CoinGecko.test.ts
- Implement Coingecko client to retrieve RBTC price
- Coinbase client doesn't support RBTC any more
> PP-753: Implement coingecko pricer 

- src/api/pricer/BaseExchangeApi.ts
- src/api/pricer/RdocExchange.ts
- src/api/pricer/StableCoinExchange.ts
- src/api/pricer/USDRIFExchange.ts
- src/api/pricer/index.ts
- src/pricer/utils.ts
- test/api/pricer/RdocExchange.test.ts
- test/api/pricer/USDRIFExchange.test.ts
- Add an exchange that returns the USDRIF price
- USDRIF isn't supported
> PP-838: add support for USDRIF
